version: 6.0.0-beta-{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
clone_folder: C:\projects\CacheManager\
init:
- cmd: if "%APPVEYOR_REPO_BRANCH%" == "master" (set VersionSuffix=) else (set VersionSuffix=beta)
environment:
  BuildNumber: $(APPVEYOR_BUILD_NUMBER)
install:
- ps: C:\projects\CacheManager\tools\redis\install-service.cmd
before_build:
- cmd: dotnet restore
build:
  project: CacheManager.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: "dotnet pack -o C:\\projects\\CacheManager\\artifacts -c Release src\\CacheManager.Core \ndotnet pack -o C:\\projects\\CacheManager\\artifacts -c Release src\\CacheManager.Microsoft.Extensions.Caching.Memory \ndotnet pack -o C:\\projects\\CacheManager\\artifacts -c Release src\\CacheManager.Microsoft.Extensions.Configuration \ndotnet pack -o C:\\projects\\CacheManager\\artifacts -c Release src\\CacheManager.Microsoft.Extensions.Logging \ndotnet pack -o C:\\projects\\CacheManager\\artifacts -c Release src\\CacheManager.Serialization.Json \ndotnet pack -o C:\\projects\\CacheManager\\artifacts -c Release src\\CacheManager.StackExchange.Redis \ndotnet pack -o C:\\projects\\CacheManager\\artifacts -c Release src\\CacheManager.SystemRuntimeCaching \ndotnet pack -o C:\\projects\\CacheManager\\artifacts -c Release src\\CacheManager.Serialization.DataContract"
artifacts:
- path: artifacts\*.nupkg
  name: nugets
deploy:
- provider: NuGet
  server: https://www.myget.org/F/jkatsiotis/api/v2/package
  symbol_server: https://www.myget.org/F/jkatsiotis/api/v2/package
  artifact: nugets
